[tool.poetry]
name = "emotional-arousal-extraction"
version = "0.1.0"
description = ""
authors = ["Matthias Boeker <matthias.boeker@icloud.com>"]
readme = "README.md"
packages = [{include = "emotional_arousal_extraction"}]

[tool.poetry.dependencies]
python = " >=3.8,<3.9.7"
pandas = "^1.4.4"
numpy = "^1.23.2"
pytest = "^7.1.2"
black = "^22.6.0"
scipy = "^1.9.1"
scikit-learn = "^1.1.2"
streamlit = "^1.12.2"
matplotlib = "^3.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
